build:
  image: latest

version: 2

submodules:
  include: all

formats:
  - htmlzip

conda:
  environment: .rtd-environment.yml

python:
  system_packages: true
  version: 3.7
  install:
    - method: pip
      path: .
