branches:
  only:
    - travistest
language: python
python:
  - 2.7
  
before_install:
  - sudo apt-get install libcfitsio3-dev
# command to install dependencies
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"
# command to run tests
script:
  - cd healpy/test/data
  - bash get_wmap_maps.sh
  - cd ../../../
  - bash testbuild.sh
notifications:
  email: false
